#!/bin/sh
set -e
cd /pkg
for cfg in *
do
    cd /pkg/$cfg
    for pkg in *
    do
        [ "$pkg" = "busybox" ] && continue
    
        for tool in $pkg/*/usr/bin/*
        do
            tool=`basename "$tool"`
            [ "$tool" != "*" -a "$tool" != "busybox" ] && echo "$tool:$pkg"
        done
    done
done > .tools
exit 0
