#!/bin/sh
set -e
cd /pkg
for cfg in *
do
    cd /pkg/$cfg
    for pkg in *
    do
        [ "$pkg" = "busybox" ] && continue
        ( echo "$pkg" | grep 'rename$' ) && continue

        for ver in $pkg/*/
        do
            ( echo "$ver" | grep '\/a' ) && continue
            if [ ! -e $ver/.tools ]
            then
                for tool in $ver/usr/bin/*
                do
                    tool=`basename "$tool"`
                    [ "$tool" != "*" -a "$tool" != "busybox" ] && echo "$tool:$pkg"
                done > $ver/.tools
            fi

            cat $ver/.tools
        done
    done
done > .tools
exit 0
