#!/bin/sh
die() {
    echo "$1"
    exit 1
}

todeps() {
    for dep in `cat`
    do
        dep=`echo "$dep" | sed 's/:.*//'`
        if expr "$dep" : '.*[=><]' > /dev/null 2> /dev/null
        then
            echo -n " $dep"
        else
            echo -n " $dep" | sed 's/-\(\[[0-9\-]*\]\)*[^\-]*$//'
        fi
    done
}

PKGNAME="$1"
DEPENDS="$2"
BUILD_DEPENDS="$3"
USE_TOOLS="$4"
shift; shift; shift; shift

# FIXME: this is so slow, need to keep this in a DB of some sort
tool_regex='^('`echo "$USE_TOOLS" | sed 's/:[^: ]*//g ; s/[^A-Za-z0-9\-_ ]/---/g ; s/ /:|/g'`')'
TOOL_DEPENDS=`egrep "$tool_regex" /pkg/.tools | sed 's/^[^:]*://' | sort | uniq`

SNPS_DEPENDS=`echo "$DEPENDS" | todeps`
export SNPS_DEPENDS
SNPS_BUILD_DEPENDS=`echo "$BUILD_DEPENDS" | todeps`
SNPS_BUILD_DEPENDS="$SNPS_BUILD_DEPENDS $TOOL_DEPENDS"
export SNPS_BUILD_DEPENDS
SNPS_PKGNAME="$PKGNAME"
export SNPS_PKGNAME
SNPS_PKG="`echo $SNPS_PKGNAME | sed 's/-[^-]*$//'`"
export SNPS_PKG
SNPS_PKG_VER="`echo $SNPS_PKGNAME | sed 's/^.*-//'`"
export SNPS_PKG_VER

exec with -r minimal pkgsrc $SNPS_DEPENDS $SNPS_BUILD_DEPENDS -q $SNPS_PKG/a.$SNPS_PKG_VER -- env "$@"
